#
# Makefile for development
#

PY_SRC_PATH=$(HOME)/projects/yjw/python

RASMUS_SRC_FILES = __init__ \
		   tablelib \
		   timer \
		   treelib \
		   stats \
		   util \
		   textdraw \
		   linked_list \
		   plotting

RASMUS_PLY_FILES = README \
		   __init__.py \
		   lex.py \
		   yacc.py

COMPBIO_SRC_FILES = __init__ \
		   fasta \
		   seqlib \
		   phylo \
		   coal \
		   birthdeath \
                   phyloDLC

VERSIONS = versions.txt

# all
all: includepy

# copy subset of python modules for packaging with dlcpar
includepy: versions
	for mod in $(RASMUS_SRC_FILES); do \
		cp $(PY_SRC_PATH)/rasmus/$${mod}.py python/dlcpar/deps/rasmus/$${mod}.py; \
	done

	mkdir -p python/dlcpar/deps/rasmus/ply
	for mod in $(RASMUS_PLY_FILES); do \
		cp $(PY_SRC_PATH)/rasmus/ply/$${mod} python/dlcpar/deps/rasmus/ply/$${mod}; \
	done

	mkdir -p python/dlcpar/deps/compbio
	for mod in $(COMPBIO_SRC_FILES); do \
		cp $(PY_SRC_PATH)/compbio/$${mod}.py python/dlcpar/deps/compbio/$${mod}.py; \
	done

# copy versions
versions:
	touch $(VERSIONS)

	echo -ne "compbio\t" >> $(VERSIONS)
	cd $(PY_SRC_PATH)/compbio; git rev-parse HEAD >> $(CURDIR)/$(VERSIONS)

# clean
clean:
	rm versions.txt
	rm python/dlcpar/*.pyc
	rm -r python/dlcpar/deps

