#
# Makefile for development
#

PY_SRC_PATH=$(HOME)/projects/compbio/python

RASMUS_SRC_FILES = __init__ \
		   tablelib \
		   textdraw \
		   timer \
		   treelib \
		   stats \
		   util \
		   colors \
		   svg

COMPBIO_SRC_FILES = __init__ \
		   phylo \
		   phyloDLC \
		   treesearch \
		   coal \
		   birthdeath

VERSIONS = versions.txt

# all
all: includepy

# copy subset of python modules for packaging with dlcpar
includepy: versions
	mkdir -p python/dlcpar/deps/rasmus
	for mod in $(RASMUS_SRC_FILES); do \
		cp -p $(PY_SRC_PATH)/rasmus/$${mod}.py python/dlcpar/deps/rasmus/$${mod}.py; \
	done

	mkdir -p python/dlcpar/deps/compbio
	for mod in $(COMPBIO_SRC_FILES); do \
		cp -p $(PY_SRC_PATH)/compbio/$${mod}.py python/dlcpar/deps/compbio/$${mod}.py; \
	done

# copy versions
versions:
	touch $(VERSIONS)

	echo -ne "compbio\t" >> $(VERSIONS)
	cd $(PY_SRC_PATH)/compbio; git rev-parse HEAD >> $(CURDIR)/$(VERSIONS)

# clean
clean:
	rm versions.txt
	rm python/dlcpar/*.pyc
	rm -r python/dlcpar/deps

